<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MtiUserSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'username' => 'admin001',
                'password' => password_hash('admin123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Ustadz Fauzi Rahman',
                'kelas' => NULL,
                'role' => 'admin',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123001',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Abdul Malik',
                'kelas' => '12 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123002',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Ahmad Zaidan',
                'kelas' => '12 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123003',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Muhammad Iqbal',
                'kelas' => '12 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123004',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Fatimah Az-Zahra',
                'kelas' => '12 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123005',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Yusuf Al-Majid',
                'kelas' => '11 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123006',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Khadijah Binti Khuwailid',
                'kelas' => '11 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123007',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Ali bin Abi Thalib',
                'kelas' => '11 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123008',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Husna Binti Nu\'man',
                'kelas' => '10 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123009',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Faris bin Ghanim',
                'kelas' => '10 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123010',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Aisyah Binti Abu Bakar',
                'kelas' => '10 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123011',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Umar bin Khattab',
                'kelas' => '12 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123012',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Zahra Binti Muhammad',
                'kelas' => '12 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123013',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Ibrahim bin Adham',
                'kelas' => '11 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123014',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Maryam Binti Imran',
                'kelas' => '11 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123015',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Daud bin Sulaiman',
                'kelas' => '11 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123016',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Siti Hajar',
                'kelas' => '10 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123017',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Ishaq bin Ibrahim',
                'kelas' => '10 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123018',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Rafiq bin Yusuf',
                'kelas' => '10 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123019',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Hana Binti Salam',
                'kelas' => '12 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'username' => '123020',
                'password' => password_hash('password123', PASSWORD_BCRYPT),
                'nama_lengkap' => 'Khalid bin Walid',
                'kelas' => '12 MA',
                'role' => 'santri',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('mti_users')->insertBatch($data);
    }
}
